### PR TITLE
feat: CI build and test pipeline

### PR DESCRIPTION
**Pull request by wdconinc**
This PR adds a build and testing pipeline, using both gcc and clang as reference compilers. It runs the mock data generator and subsequent analysis. No validation on the analysis results is performed. This PR also adds a clang-tidy analysis for modified code segments (presumably some suggestions will appear on this PR).

TODO:
- [ ] merge #13 and rebase, as this PR is built on top of it.

### CODE REVIEW

**Comment by wdconinc** [comment]
Awaiting actions from being enabled here, https://github.com/wdconinc/japan-MOLLER/actions/runs/9166948693 has the intended output.

**Comment by wdconinc** [comment]
@paulmking @hansenjo FYI

**Comment by hansenjo** [comment]
JLab's cpu allowance for GitHub workflows is very limited. The plan is to run CI on the new site code.jlab.org, which is in beta. We should hold off with this.

If you have time, look into setting up web hooks for triggering CI runs at JLab. The SciComp folks are supposed to research this, but at the rate they are going, it might be a long while. The other halls and probably EIC are also interested in such a GitHub->JLab link.

**Comment by hansenjo** [comment]
Also, I suggest we keep our CI workflows independent of CERN software collections. As a rule of thumb, make runtime environments as standalone as possible or at least only dependent on things we control. (JLab does export application software via CVMFS, too.)

**Comment by wdconinc** [comment]
> JLab does export application software via CVMFS, too.

Sure, where is the documentation for that?

**Comment by wdconinc** [comment]
> allowance for GitHub workflows is very limited

Irrelevant for PRs where this is going against the submitter's CPU allocation.

**Comment by hansenjo** [comment]
> > JLab does export application software via CVMFS, too.
> 
> Sure, where is the documentation for that?

Not sure. Why not file a helpdesk ticket along with a suggestion to add the documentation to the Knowledge base.

**Comment by wdconinc** [comment]
@wmoore28 Can you point to the kb docs on how to use JLab application software over cvmfs? All there appears to be is https://jlab.servicenowservices.com/scicomp?id=kb_article_view&sys_kb_id=4aa518981b7dc110a888ea4ce54bcb79 which doesn't actually help in loading any software environment.

**Comment by wdconinc** [comment]
> Could we then find ourselves in a position where a CI job doesn't run because the particular submitted (presumably a pretty active person) is out of their minutes?

You are never "out of minutes". You get 20 job slots at 4 cores. If they are all in use then new jobs are queued until some jobs finish. I am using GitHub actions extensively and I have never experienced the limits to be ... limiting.

Ref. https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

**Comment by hansenjo** [comment]
> > Could we then find ourselves in a position where a CI job doesn't run because the particular submitted (presumably a pretty active person) is out of their minutes?
> 
> You are never "out of minutes". You get 20 job slots at 4 cores. If they are all in use then new jobs are queued until some jobs finish. I am using GitHub actions extensively and I have never experienced the limits to be ... limiting.
> 
> Ref. https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

Thanks for the link. It seems like the policies have changed since I last looked at this. Interesting.

**Comment by wdconinc** [comment]
> we might want to squash those various trial and error commits, maybe rebase the whole thing into a one or two commits

I was assuming squash merges would emerge as the default policy, so yeah this should be squash merged. If you have a CI validation setup, then regular merging isn't as useful since you cannot guarantee individual commits pass validation.

**Comment by wdconinc** [comment]
Rebased on current main.

**Comment by wdconinc** [comment]
I can add that having a dual strategy of both gitlab and github pipelines is the most useful. Even if code.jlab.org becomes a reality, we would still want to maintain the ability to run tests on github. This is just a matter of redundancy because otherwise you are dead in the water when either github actions or code.jlab.org goes down. For EIC we have found that to be very important for throughput (because things like code.jlab.org will go down when you need them most, since our needs are going to be correlated to the load on those systems).

**Comment by hansenjo** [comment]
> I can add that having a dual strategy of both gitlab and github pipelines is the most useful. Even if code.jlab.org becomes a reality, we would still want to maintain the ability to run tests on github. This is just a matter of redundancy because otherwise you are dead in the water when either github actions or code.jlab.org goes down. For EIC we have found that to be very important for throughput (because things like code.jlab.org will go down when you need them most, since our needs are going to be correlated to the load on those systems).

That sounds good. Regarding code.jlab.org, let's wait and see (and I will lobby for a community-friendly configuration).

**Pull request merged**
